MOTIVATION_BUTTON = 'Give motivation'
UNFOLLOWERS_BUTTON = 'Who didn\'t follow back'
CONVERT_CURRENCIES_BUTTON = 'Convert money'
LIST_OF_BUTTONS = [MOTIVATION_BUTTON, CONVERT_CURRENCIES_BUTTON, UNFOLLOWERS_BUTTON]

ADMIN_IDS = [2048624017]
ADMIN_ADD_MOTIVATION_BUTTON = 'Add motivation'
LIST_OF_ADMIN_BUTTONS = [ADMIN_ADD_MOTIVATION_BUTTON]


START_COMMAND = '/start'
HELP_COMMAND = '/help'
BUTTONS_COMMAND = '/buttons'

USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko)'
